### ISSUE TITLE
Roles -> Group Mapping Issue Overwrites User's Custom Link Preferences

### ISSUE THREAD

**Issue by reynoldsalec** [rjbain/dgreat#365]
**Description**

From @drmyers1 [on Slack](https://usf-web-services.slack.com/archives/C9PH3NHTQ/p1533851179000210):

A user can login and add a personal quick link and can also customize their links by flagging and unflagging.  However, we found that when user logs back into the system the personal links and customization no longer display on their list of links.

@mjuarez2 dug a little deeper and traced the problem to the dgreat group module.  Specifically it seems to be connected to the dgreat_group_user_login function and RoleGroupMapper.  He was able to test this out by commented out this function and could see that the user retains their links and customization.

It looks like on login the links are "unflagged," which prevents the user from keeping any of their pervious personalization. Do you have suggestions for fixing this?

**Comment by drmyers1** [comment]
@reynoldsalec yes, this description looks correct.

**Comment by nicholas-kebbas** [comment]
Couple Comments so far:

1. Favorite Links order (and the links themselves) seem to change upon every save.
2. Users not seeing their list of links on the dashboard.
3. Adding a link doesn't add it to my own personal links

As a user with links, however, my changes (removals/reorderings) seem to persist.

**Comment by mjuarez2** [comment]
Here's the link to the view where the add/manage links can be edited:

https://pr-368-dgreat.pantheonsite.io/admin/structure/views/view/quick_links/edit/block

**Comment by rjbain** [comment]
> 2\. Users not seeing their list of links on the dashboard

@mjuarez2 @nicholas-kebbas It sounds like this might be an issue with the view, since it wasn't an issue we previously encountered. Could one of you take a look at it? Thanks!

**Comment by mjuarez2** [comment]
I tested the dgreat_group module on test. It took 2 hrs 11 minutes to update the Student group. The process did not error out. I pushed the module to live, and it is currently disabled. @labboy0276 @reynoldsalec @rjbain @nicholas-kebbas

**Comment by mjuarez2** [comment]
I have the dashboard template with the correct Quick Links/Favorite Links views here: https://pr-371-dgreat.pantheonsite.io This is how it should look.

The disappearing quick link bug can also be reproduced here. I was not able to see all the Quick Links or Favorite Apps at first until I deleted the account I was testing on and then added it back again, assigning the appropriate roles and groups to it. Once I did that, they all appeared again.
@dustinleblanc @rjbain

**Comment by dustinleblanc** [comment]
@mjuarez2 yep I think that @labboy0276 added the default links to a user on account creation so that makes sense

**Comment by nicholas-kebbas** [comment]
@rjbain @dustinleblanc @mjuarez2 Hi guys, was able to add but ran into some issues. Will elaborate tomorrow but for now:

dfaculty, demployee, d2groups, 
Add a new myLink works (and adds to view)
Persists after logout works

Do not get their defaults. 
Upon account deletion, still do not get their defaults when their account is created.

Rearrange myLinks
Works

Rearrange Top Apps
Does not rearrange correctly after you save. Order seems random.

For some reason it looks like only student is not able to see their link once they add it.

dstudent
Add Link
Does not work as expected (adds to database but does not add to view)

* there was a mention that a user only gets their defaults upon account creation. We want them to make sure they get defaults upon each login, and that existing users will get their defaults.

Add a default to group - Waiting to see how that goes

**Comment by dustinleblanc** [comment]
Per Slack discussion, looks like we've got some more features to test out to make sure they are working

**Comment by rjbain** [comment]
@dustinleblanc thanks for your help with this. We met and discussed the issue we're having with the default links. Since there is likely to be a performance issue during login if we want the default links to be updated when a user logs in, we're proposing moving default links to a separate view that we can put on the dashboard. This would simply display links based on the user's role that we could manually update when needed. Does this sound like it would solve the issue?

So, aside from the default links issue, it looks like we're still not able to rearrange the Top Apps and we're not able to save new myLinks for the dstudent test user (user with the student role). @nicholas-kebbas please chime in if that's not correct.

Lastly, it seems that we never got the dashboard template change up to your MD. @mjuarez2 could you please work with @dustinleblanc to get his MD up to date? The correct template is here on this branch: https://pr-371-dgreat.pantheonsite.io/.

Thanks, guys.

**Comment by dustinleblanc** [comment]
@rjbain re: the template change, yeah I see a funky diff in my PR for that which I wasn't expecting, I must not have rebased properly, planning to fix that shortly.

Good choice re: default links, I think we could visually smooth them together, however then maybe sorting would get bonkers? Not sure. I'll see if I can have that template snafu sorted shortly

**Comment by rjbain** [comment]
Thanks @dustinleblanc. We discussed having the defaults and myLinks in the same view, but decided it would be too confusing for the user and likely more difficult to implement.

**Comment by dustinleblanc** [comment]
@rjbain so should I just stay unconcerned with the default links and continue with just making sure re-ordering works? I remember that was a long running crazy issue John worked on

**Comment by rjbain** [comment]
@dustinleblanc Yes, please. The reordering of the Top Apps on the left side isn't working. Also, for some reason the dstudent account can't save new myLinks. I checked that account and it does have the student role and student group, so there doesn't seem to be anything wrong with the account. Any ideas? Thanks.

**Comment by rjbain** [comment]
@dustinleblanc I deleted the dstudent (student role) account and then logged in via CAS. I was able to add and rearrange myLinks afterward, so I think all of the issues are resolved with myLinks. @nicholas-kebbas feel free to close this if you see fit. Thanks guys.

**Comment by nicholas-kebbas** [comment]
@dustinleblanc Yeah I tested and had the same result, so that's good. @rjbain  We should keep in mind that we need to test existing users pretty thoroughly to see if them not being able to add a myLink is a widespread problem, but we can't really address that until we're live so will close. Thanks guys!
