### ISSUE TITLE
Services Catalog Feedback

### ISSUE THREAD

**Issue by drmyers1** [rjbain/dgreat#66]
1. i tested editing an application and compare with the productions site.  http://pr-tandem-dgreat.pantheonsite.io/node/13076/edit?destination=/admin/content%3Ftitle%3Dbanner%26type%3Dusf_service%26status%3DAll%26langcode%3DAll 
Here are some questions:
A. url was not included in the migration.  Will that need to be added manually?  On production is was listed in the permalink section and on the new site it is under url path setting.
B. can we enable the WYSIWYG view for the service description. Currently it only has basic html, restricted html and full html.
C. Under Audience the different roles are listed as radio buttons on the new site but on production, they are a check box.  It should allow for multiple selections

2. Is there a page that lists out all the services, similar to what we have on production
https://myusf.usfca.edu/its/applications-services  
Or is this being worked on? i could not find in content area.

3. Is there a how do it page that feeds in all the how do i questions, like on production
https://myusf.usfca.edu/its/how-do-i
Or is this being worked on? I could not find in content area

**Comment by labboy0276** [comment]
@drmyers1 

1:
A. Yes that is a seperate migration, there is a url alias migration task that will need to get done once nodes are migrated
B. We would have to setup that text format, you can create a seperate task to handle that if you want
C. Fixed
2 & 3 On these two, the team is figuring out to handle staticy type pages since the structure will be different in d8.  In the interim the views are there: /admin/structure/views/view/services.  We just have no place to put them yet.

**Comment by drmyers1** [comment]
@rjbain @mjuarez2 @nicholas-kebbas we need discuss the presentation of the 2 & 3 in my feedback.

@labboy0276 it looks like the services no longer exist in the tandem branch.  Not able to test that item C is fixed.

**Comment by drmyers1** [comment]
@labboy0276 

i do not see any of the applications listed on the page @rjbain created.
http://dev-dgreat.pantheonsite.io/its/applications-services

I also checked the tandem branch and do see a page.  Here is the production link to compare:  https://myusf.usfca.edu/its/applications-services

- The list of applications should show title and short description
- There also needs to be a filter (student, faculty and staff) for the applications.
- There needs to be a search at the top of the list of applications
- Also not able to find a "How Do I" page.  Here is an example on production: https://myusf.usfca.edu/its/how-do-i
- The "How Do I" page should show all the different applications and the How Do I resources for each.
- There should also be an area that can display a static list of the top student how do i and top fac/staff how do i

Please let me know if you have any questions.

**Comment by drmyers1** [comment]
@labboy0276 

i tested the search on the main application services page.
http://pr-tandem-dgreat.pantheonsite.io/its/applications-services

When i search by one of the service synonyms i get no results.  I tested with the term "Banner".  The synonym is list in the Administrative System Suite (Banner) service.

When I click to view a service it should display Title, Service Description, Policies, How Do I, Training, and Audience.  It should not display the synonyms.  Synonyms should only be used for search.
Here is an example on the tandem branch and the production site to show the difference.
http://pr-tandem-dgreat.pantheonsite.io/node/13076
https://myusf.usfca.edu/services/administrative-system-suite-banner

I am not able to see the "How Do I" page that pulls in all the How Do I's.  Here is the page on production
https://myusf.usfca.edu/its/how-do-i

Please let me know if you have any questions.

**Comment by labboy0276** [comment]
@drmyers1 the how do i page is here right now: http://dev-dgreat.pantheonsite.io/how-do-i

**Comment by labboy0276** [comment]
I fixed the url of the how do i on the tandem branch real quick

**Comment by labboy0276** [comment]
@drmyers1 Ok I am working on the search, it doesnt seem to work right no matter what I do.  As far as the display goes for the services themselves.  The issue was in the migration the text format wasn't migrated right, so it wont display.  I fixed it locally, but I have to remigrate the services for it to show up right.  You can manually go in and select the text format on the body for now.

**Comment by drmyers1** [comment]
@labboy0276 thank you for fixing the How Do I link on dev.  I took a look at the How Do I page.  Can we put the How Do I links on separate lines instead separated by comma?  Also some of the services show up on the same line.  Can also have each service on a separate line?  See Digital Signage and Directory Services.  Also see Hardware and Instructional Design for examples.
http://dev-dgreat.pantheonsite.io/its/how-do-i

**Comment by drmyers1** [comment]
@labboy0276 thank you.  i will test once it gets pushed to dev.

**Comment by drmyers1** [comment]
@labboy0276 i think something changed because the How Do I page now has the list comma separated, instead of being on separate line.
http://dev-dgreat.pantheonsite.io/its/how-do-i

Also i noticed that the service details dont have all the fields yet (Title, Service Description, Policies, How Do I, Training, and Audience).  Also it should not display the synonyms in the details view. Synonyms should only be used for search.
Here is an example on dev and the production site to show the difference.
http://dev-dgreat.pantheonsite.io/node/13076
https://myusf.usfca.edu/services/administrative-system-suite-banner

**Comment by labboy0276** [comment]
Odd, somehow all my work got reverted, oy vay @drmyers1

**Comment by labboy0276** [comment]
@drmyers1 I added back in all the config that got wiped out, should be ok now.

**Comment by drmyers1** [comment]
@labboy0276 i am still not seeing the changes reflected on dev.

**Comment by labboy0276** [comment]
@drmyers1 looks like it was an issue with the config workflow on usf's end, rob will address it with the team

**Comment by rjbain** [comment]
@labboy0276 I'm sorry about the workflow issues. We should be straightened out now. Can we push forward with this?

**Comment by labboy0276** [comment]
@drmyers1 yes this should be back on dev now

**Comment by drmyers1** [comment]
@labboy0276 it does not look like the changes are back for the service catalog.  I also dont see the changes on the service details.  On the How Do I page i get the following error:
The website encountered an unexpected error. Please try again later.

Here is a summary of the changes:
The How Do I page should have the how do i's on a separate line, not comma separated.
http://dev-dgreat.pantheonsite.io/its/how-do-i

The service details dont have all the fields yet (Title, Service Description, Policies, How Do I, Training, and Audience). Also it should not display the synonyms in the details view. Synonyms should only be used for search.
Here is an example on dev and the production site to show the difference.
http://dev-dgreat.pantheonsite.io/node/13076
https://myusf.usfca.edu/services/administrative-system-suite-banner

**Comment by rjbain** [comment]
@labboy0276 It also looks like blocks all the blocks are showing up on all the pages

**Comment by rjbain** [comment]
@labboy0276 I'm looking through the db logs and wondering if cron could be causing problems?

**Comment by labboy0276** [comment]
@rjbain that is odd, sorry was heads down on something

**Comment by labboy0276** [comment]
@drmyers1 I fixed the how-do-i page real quick.  I will have to manually redo all this stuff again since something just isnt kosher.

**Comment by labboy0276** [comment]
OK @drmyers1 I added the services back in, it is checking the PR now

**Comment by rjbain** [comment]
@labboy0276 If something isn't kosher we should probably try to figure out what it is. If nobody merged anything into master then could it have been?

**Comment by labboy0276** [comment]
I dont think I added back in all the config this last time @rjbain

**Comment by drmyers1** [comment]
@labboy0276 should i hold off on testing?  at first glance, i see the top student questions and top fac/staff questions.  I am noticing that the How Do I's are still comma separated and the service details are still missing some of the fields.  Could those changes not have been included with the recent config changes?

**Comment by labboy0276** [comment]
@drmyers1 maybe it didnt hit yet?  looks ok now:

![service](https://user-images.githubusercontent.com/5560907/40694236-9ea7764e-6389-11e8-88b9-5f6fb8497d58.jpg)

**Comment by labboy0276** [comment]
also, on the services @drmyers1 I need to remigrate the content for it to be correct

**Comment by drmyers1** [comment]
@labboy0276 here is my feedback for the service catalog:

How Do I
- I see the How Do I listing is correct.
- Can we please have the How Do I links open in a new window

Application Services
- Did a search for the term "Banner" and get no results
- "Banner" is both in one of the titles and in the synonym listing 
- I searched again using the term "Training" and I do see results
- The service details should display the following fields (Title, Service Description, Policies, How Do I, Training, and Audience). 
- I edited Administrative System Suite (Banner) and I see that some of the above mentioned fields are populated but they dont display to the details view.  Here is an example on dev and the production site to show the difference of the view.
http://dev-dgreat.pantheonsite.io/node/13076
https://myusf.usfca.edu/services/administrative-system-suite-banner

Please let me know if you have any questions.

**Comment by labboy0276** [comment]
@drmyers1 you forgot to set the text format on the body, I fixed it now it shows up correctly.  I need to re-import all the node content on the site regardless as the body formats didn't map right.  

As far as the search goes I am at a loss because it looks to be setup correctly.  May have someone else take a look at it.  

The regressions on the other items are due to the config workflow sadness that keeps making me redo everything.

**Comment by rjbain** [comment]
@labboy0276 are you saying that your config got wiped out again?

**Comment by labboy0276** [comment]
@rjbain nope, I was just saying that things that were there and then arent were because of that.  I probably missed a thing or two redoing them.

**Comment by drmyers1** [comment]
@labboy0276 I have been testing with application services that were initially imported.  Is there not a way to apply a default text format for the body content or will that always be the case for any new application service that is added?

I dont see the title and audience displaying on the details view of any application.  Can we add those in?
http://dev-dgreat.pantheonsite.io/node/13114

On the application listing view there is Digital Education that is indented and is different from all the others.  Not sure why?
http://dev-dgreat.pantheonsite.io/its/applications-services

Also some the applications listing seem to be in alpha order and others seem to show up in random order.  Can we have it all show in alpha order and combine if multiple roles are selected in the view? 

Any help on the search would be appreciated. 

Please let me know if you have any questions.

**Comment by labboy0276** [comment]
@drmyers1 When I remigrate the content, it will fix the default text format issue.  

For the title, it is a block, they did page title weird in D8.  So that needs to be setup tertiary to this task.  I fixed the audience though.  

I dont see the Digital Education indentation any longer, maybe it got fixed?

I fixed the alpha sort on the views as well.

**Comment by drmyers1** [comment]
@labboy0276 i will take a look.

**Comment by drmyers1** [comment]
@labboy0276 It looks like Digital Education only displays when you are logged into Drupal.  I see that the text is still indented.  I am attaching a screenshot.  Tested on mac using chrome, firefox, and safari.  All browsers show the indent.  This should display without having to be logged in.
![screen shot 2018-06-07 at 8 48 25 am](https://user-images.githubusercontent.com/37413213/41111502-fabe70b0-6a30-11e8-85f0-f463b4c83500.png)

**Comment by labboy0276** [comment]
@drmyers1 ah ok, the digital education node isn't published that is why that is happening.

**Comment by drmyers1** [comment]
@labboy0276 @reynoldsalec any updates on the search?

**Comment by drmyers1** [comment]
@labboy0276 @reynoldsalec just want to check on the status of search.  any updates?  @labboy0276 do you plan on merging all other service catalog changes when the search is done?

**Comment by reynoldsalec** [comment]
@labboy0276 I had a chance to look at this and think it's due to the search index not being configured for case sensitivity correctly. I made a simple test index to try it out, along with a test view on the Dev site (you should obviously nuke this once you deploy the changes in your Block View): http://dev-dgreat.pantheonsite.io/admin/structure/views/view/test_view

Search for "banner" on that View gives you Service content type results with banner in them, as you would expect. Compare http://dev-dgreat.pantheonsite.io/admin/config/search/search-api/index/services/processors to the existing search index's processors page to see what I configured (HTML filter may not be necessary, just case sensitivity).

@drmyers1 this is a small tweak, think we should have it wrapped up shortly!

**Comment by labboy0276** [comment]
@drmyers1 @reynoldsalec yup that did it, good catch @reynoldsalec .  I am pushing this up to dev now

**Comment by drmyers1** [comment]
@labboy0276 @reynoldsalec the search is working as expected on dev.  Thank you!
